export const ArrayDiente = [
	{
		id: 'num18',
		numero: 18,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Tercer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num17',
		numero: 17,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Segundo Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num16',
		numero: 16,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Primer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num15',
		numero: 15,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Segundo Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num14',
		numero: 14,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Primer Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num13',
		numero: 13,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Canino',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num12',
		numero: 12,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Incisivo Lateral',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num11',
		numero: 11,
		cuadrante: 'Primer Cuadrante',
		nombre: 'Incisivo Central',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num21',
		numero: 21,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Incisivo Central',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num22',
		numero: 22,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Incisivo Lateral',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num23',
		numero: 23,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Canino',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num24',
		numero: 24,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Primer Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num25',
		numero: 25,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Segundo Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num26',
		numero: 26,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Primer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num27',
		numero: 27,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Segundo Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num28',
		numero: 28,
		cuadrante: 'Segundo Cuadrante',
		nombre: 'Tercer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num48',
		numero: 48,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Tercer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num47',
		numero: 47,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Segundo Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num46',
		numero: 46,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Primer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num45',
		numero: 45,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Segundo Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num44',
		numero: 44,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Primer Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num43',
		numero: 43,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Canino',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num42',
		numero: 42,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Incisivo Lateral',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num41',
		numero: 41,
		cuadrante: 'Cuarto Cuadrante',
		nombre: 'Incisivo Central',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num31',
		numero: 31,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Incisivo Central',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num32',
		numero: 32,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Incisivo Lateral',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num33',
		numero: 33,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Canino',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num34',
		numero: 34,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Primer Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num35',
		numero: 35,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Segundo Premolar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num36',
		numero: 36,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Primer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num37',
		numero: 37,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Segundo Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
	{
		id: 'num38',
		numero: 38,
		cuadrante: 'Tercer Cuadrante',
		nombre: 'Tercer Molar',
		estado: 'Presente en Boca',
		hallazgo: '',
		caras: {
			Vestibular: '',
			Oclusal: '',
			Lingual: '',
			Mesial: '',
			Distal: '',
		},
	},
];
