export const ArrayDiente = [
	{
		id: 'num18',
		numero: 18,
		nombre: 'Tercer Molar',
		caras: [
			{
				Todas_Las_Caras: 'Caries',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num17',
		numero: 17,
		nombre: 'Segundo Molar',
		caras: [
			{
				Todas_Las_Caras: 'Restauracion Defectuosa',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num16',
		numero: 16,
		nombre: 'Primer Molar',
		caras: [
			{
				Todas_Las_Caras: 'Endodoncia',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num15',
		numero: 15,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num14',
		numero: 14,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num13',
		numero: 13,
		nombre: 'Canino',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num12',
		numero: 12,
		nombre: 'Incisivo Lateral',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num11',
		numero: 11,
		nombre: 'Incisivo Central',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num21',
		numero: 21,
		nombre: 'Incisivo Central',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num22',
		numero: 22,
		nombre: 'Incisivo Lateral',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num23',
		numero: 23,
		nombre: 'Canino',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num24',
		numero: 24,
		nombre: 'Primer Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num25',
		numero: 25,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num26',
		numero: 26,
		nombre: 'Primer Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num27',
		numero: 27,
		nombre: 'Segundo Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num28',
		numero: 28,
		nombre: 'Tercer Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num48',
		numero: 48,
		nombre: 'Tercer Molar',
		caras: [
			{
				Todas_Las_Caras: 'Caries',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num47',
		numero: 47,
		nombre: 'Segundo Molar',
		caras: [
			{
				Todas_Las_Caras: 'Restauracion Defectuosa',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num46',
		numero: 46,
		nombre: 'Primer Molar',
		caras: [
			{
				Todas_Las_Caras: 'Endodoncia',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num45',
		numero: 45,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num44',
		numero: 44,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num43',
		numero: 43,
		nombre: 'Canino',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num42',
		numero: 42,
		nombre: 'Incisivo Lateral',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num41',
		numero: 41,
		nombre: 'Incisivo Central',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num31',
		numero: 31,
		nombre: 'Incisivo Central',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num32',
		numero: 32,
		nombre: 'Incisivo Lateral',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num33',
		numero: 33,
		nombre: 'Canino',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num34',
		numero: 34,
		nombre: 'Primer Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num35',
		numero: 35,
		nombre: 'Segundo Premolar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num36',
		numero: 36,
		nombre: 'Primer Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num37',
		numero: 37,
		nombre: 'Segundo Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
	{
		id: 'num38',
		numero: 38,
		nombre: 'Tercer Molar',
		caras: [
			{
				Todas_Las_Caras: '',
				Vestibular: '',
				Oclusal: '',
				Lingual: '',
				Mesial: '',
				Distal: '',
			},
		],
		Descripcion: '.....',
	},
];
