export const HallazgosArray = [
	{ id: '', name: '' },
	{ id: 'Caries', name: 'caries' },
	{ id: 'RestauraciónOk', name: 'restauración en buen estado' },
	{ id: 'RestauraciónBad', name: 'restauración defectuosa' },
	{ id: 'Movilidad', name: 'movilidad' },
	{ id: 'Corona Definitiva', name: 'corona definitiva' },
	{ id: 'Corona Temporal', name: 'corona temporal' },
	{ id: 'Fractura', name: 'fractura' },
	{ id: 'Macrodiente', name: 'macrodiente' },
	{ id: 'Microdiente', name: 'microdiente' },
	{ id: 'Giroversión', name: 'giroversión' },
	{ id: 'Ectópico', name: 'ectópico' },
	{ id: 'Implante', name: 'implante' },
	{ id: 'Ausente', name: 'ausente' },
];
